FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json .

RUN npm ci 

COPY . .

RUN npm run build

FROM node:22-alpine AS prod

WORKDIR /app

COPY package*.json .

RUN npm ci 

COPY --from=builder /app/dist/ ./dist
COPY --from=builder /app/public/ ./public
COPY .env .

EXPOSE 3000

ENTRYPOINT [ "node", "dist/index.js" ]